### PR TITLE
Fix conflict with Superpower Extension

### PR DESCRIPTION
**Pull request by neoOpus**
Added a 10s delay ad rearranged the functions calls, so now it loads after Superpower adjusted the sidebar.

### CODE REVIEW

**Comment by neoOpus** [comment]
maybe the delay requires to be adjusted by end-users so later you can (or I will do) add in the menu or TM the option to adjust it if you think it is necessary after collecting some feedbacks.

**Comment by neoOpus** [comment]
Delay should be probably of 15-20s instead

**Comment by xcanwin** [comment]
This is because superpower made excessive changes to the sidebar, causing most of the chatgpt sidebar plugins to malfunction. It's a bug in superpower 's implementation, and I know he can easily fix it. You should suggest to superpower to make fewer modifications instead of having other plugins accommodate its bug. It's unfair to propose that other plugins not start or start later, considering it's clearly a bug in superpower 's implementation. This would require all plugin authors to check superpower 's changelog daily before developing their own code.

**Comment by neoOpus** [comment]
I understand the situation, and it's meant as a temporary fix. I don't know if Saeed Ezzati will ever be nice to other developers.

**Pull request closed without merging**
